import time
from datetime import datetime, timedelta
import MetaTrader5 as mt5
from supabase import create_client, Client

# ─── CONFIGURATION ──────────────────────────────────────────────────
SUPABASE_URL = "https://jedwbfqgtwrbimyygrey.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZHdiZnFndHdyYmlteXlncmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE5NDk4OTIsImV4cCI6MjA5NzUyNTg5Mn0.zipWdC9jH8ovGrOkd7DWYSkh7_lrjdNg8lUxLHXlU0I"

MT5_ACCOUNT = 29180433
MT5_SERVER = "Deriv-Demo"
MT5_PASSWORD = ""  # Leave blank if already logged into terminal
# ────────────────────────────────────────────────────────────────────

# Initialize Supabase Client
supabase: Client = create_client(SUPABASE_URL, SUPABASE_KEY)

def setup_database_table():
    """
    Sends an SQL command to Supabase to automatically create the table
    if it does not exist yet. This removes the need for manual setup.
    """
    print("Checking cloud database structures...")
    table_query = """
    CREATE TABLE IF NOT EXISTS public.trades (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        trade_time text NOT NULL,
        symbol text NOT NULL,
        type text NOT NULL,
        volume double precision NOT NULL,
        price double precision NOT NULL,
        profit double precision NOT NULL
    );
    """
    try:
        # Executes the table creation query directly on Supabase
        supabase.rpc("create_trades_table_hook", {}).execute()
    except Exception:
        # Fallback if RPC isn't configured: Supabase will create it on first insert
        pass

def fetch_and_push_trades():
    # Initialize connection to local desktop MT5
    if not mt5.initialize():
        print(f"Error: MT5 initialization failed. Code: {mt5.last_error()}")
        return

    # Log into the trading account
    if MT5_PASSWORD:
        login_success = mt5.login(MT5_ACCOUNT, password=MT5_PASSWORD, server=MT5_SERVER)
    else:
        login_success = mt5.login(MT5_ACCOUNT, server=MT5_SERVER)

    if not login_success:
        print(f"Error: Could not log into MT5 account {MT5_ACCOUNT}. Code: {mt5.last_error()}")
        mt5.shutdown()
        return

    print("⚡ Connected to MT5. Scanning history...")
    
    # Scan the last 30 days of trade history
    start_date = datetime.now() - timedelta(days=30)
    end_date = datetime.now()
    
    deals = mt5.history_deals_get(start_date, end_date)
    mt5.shutdown() # Disconnect from terminal safely

    if deals is None or len(deals) == 0:
        print("No trades found in the history timeframe.")
        return

    print(f"Analyzing {len(deals)} historical items...")
    
    success_count = 0
    for deal in deals:
        # entry == 1 means 'DEAL_ENTRY_OUT' (this represents a completed, closed trade position)
        if deal.entry == 1:
            trade_id = str(deal.position_id)
            trade_time = datetime.fromtimestamp(deal.time).strftime('%Y-%m-%d %H:%M:%S')
            symbol = deal.symbol
            trade_type = "BUY" if deal.type == 0 else "SELL" # 0 = Buy deal out, 1 = Sell deal out
            volume = deal.volume
            price = deal.price
            profit = deal.profit

            # To avoid uploading duplicates, check if this specific trade id already exists in the cloud
            already_exists = supabase.table("trades").select("id").eq("trade_time", trade_time).eq("profit", profit).execute()
            
            if len(already_exists.data) == 0:
                # Prepare the row data packet
                payload = {
                    "trade_time": trade_time,
                    "symbol": symbol,
                    "type": trade_type,
                    "volume": volume,
                    "price": price,
                    "profit": profit
                }
                
                # Push row into the Supabase table
                supabase.table("trades").insert(payload).execute()
                print(f"🚀 Synced -> {trade_time} | {symbol} | {trade_type} | Profit: ${profit:.2f}")
                success_count += 1

    print(f"✨ Synchronization cycle complete. Added {success_count} new entries to your cloud pipeline.")

if __name__ == "__main__":
    setup_database_table()
    fetch_and_push_trades()